/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context as Context } from "./context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AnswerWhereWhereUniqueInput: { // input type
    id: string; // ID!
  }
  CreateQuestionInput: { // input type
    description: string; // String!
    name: string; // String!
  }
  CreateQuestionItemInput: { // input type
    content: string; // String!
    title: string; // String!
  }
  QuestionWhereUniqueInput: { // input type
    id: string; // ID!
  }
  createAnswerWhereUniqueInput: { // input type
    content: string; // String!
    isCorrect: boolean; // Boolean!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Answer: { // root type
    content: string; // String!
    id: string; // ID!
    isCorrect: boolean; // Boolean!
  }
  Category: { // root type
    id: string; // ID!
    name: string; // String!
  }
  Query: {};
  Question: { // root type
    content: string; // String!
    difficultyLevel: string; // String!
    id: string; // ID!
  }
  QuizHistory: { // root type
    id: string; // ID!
    score: number; // Int!
    userId: string; // ID!
  }
  User: { // root type
    id: string; // ID!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Answer: { // field return type
    content: string; // String!
    id: string; // ID!
    isCorrect: boolean; // Boolean!
  }
  Category: { // field return type
    id: string; // ID!
    name: string; // String!
  }
  Query: { // field return type
    Questions: NexusGenRootTypes['Question'][]; // [Question!]!
    question: NexusGenRootTypes['Question'] | null; // Question
  }
  Question: { // field return type
    content: string; // String!
    difficultyLevel: string; // String!
    id: string; // ID!
  }
  QuizHistory: { // field return type
    id: string; // ID!
    score: number; // Int!
    userId: string; // ID!
  }
  User: { // field return type
    id: string; // ID!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Answer: { // field return type name
    content: 'String'
    id: 'ID'
    isCorrect: 'Boolean'
  }
  Category: { // field return type name
    id: 'ID'
    name: 'String'
  }
  Query: { // field return type name
    Questions: 'Question'
    question: 'Question'
  }
  Question: { // field return type name
    content: 'String'
    difficultyLevel: 'String'
    id: 'ID'
  }
  QuizHistory: { // field return type name
    id: 'ID'
    score: 'Int'
    userId: 'ID'
  }
  User: { // field return type name
    id: 'ID'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    question: { // args
      where: NexusGenInputs['QuestionWhereUniqueInput']; // QuestionWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}